name: Allure Report to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg ca-certificates
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" \
            | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            google-chrome-stable \
            fonts-liberation \
            libnss3 \
            libxss1 \
            libatk-bridge2.0-0 \
            libgtk-3-0

      - name: Confirm Chrome
        run: |
          google-chrome-stable --version

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}

      - name: Run tests
        run: mvn clean test
        continue-on-error: true
        env:
          BASE_UI_GREEN_CITY_URL: ${{ secrets.BASE_UI_GREEN_CITY_URL }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          USER_ID: ${{ secrets.USER_ID }}
          IMPLICITLY_WAIT: ${{ secrets.IMPLICITLY_WAIT }}
          USER_LOCATION: ${{ secrets.USER_LOCATION }}
          USER_RATE: ${{ secrets.USER_RATE }}
          HEADLESS_MODE: ${{ secrets.HEADLESS_MODE }}

      - name: Generate Allure Report
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
          tar -xzf allure.tgz
          ./allure-2.25.0/bin/allure generate allure-results -o allure-report --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
