name: Main Tests with Allure History

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}

      - name: Run tests (main)
        run: mvn clean test -DsuiteXmlFile=src/test/resources/testng.xml
        continue-on-error: true
        env:
          BASE_UI_GREEN_CITY_URL: ${{ secrets.BASE_UI_GREEN_CITY_URL }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          USER_ID: ${{ secrets.USER_ID }}
          IMPLICITLY_WAIT: ${{ secrets.IMPLICITLY_WAIT }}
          USER_LOCATION: ${{ secrets.USER_LOCATION }}
          USER_RATE: ${{ secrets.USER_RATE }}
          HEADLESS_MODE: ${{ secrets.HEADLESS_MODE }}

      - name: Load previous Allure history
        run: |
          git fetch origin gh-pages
          git checkout origin/gh-pages -- main/history || true
          mkdir -p target/allure-results
          cp -r main/history target/allure-results/history || true

      - name: Generate Allure Report
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
          tar -xzf allure.tgz
          ./allure-2.25.0/bin/allure generate target/allure-results -o allure-report --clean

      - name: Deploy MAIN report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
          destination_dir: main
          keep_files: true  # Важливо, щоб звіти різних PR не видаляли один одного
          enable_jekyll: false # Вимикає Jekyll, щоб він не ігнорував технічні папки Allure
